# embed_templates.py
"""
Embeds .docx templates as base64-encoded strings into templates_base64.py
Run this script whenever you update the template files.
"""

import base64
import os


def embed_templates():
    """
    Read .docx templates and create templates_base64.py with base64-encoded content.
    """
    templates_dir = "templates"
    designer_path = os.path.join(templates_dir, "Designer_Onboarding_Template.docx")
    installer_path = os.path.join(templates_dir, "Installer_Onboarding_Template.docx")
    
    # Check if template files exist
    if not os.path.exists(designer_path):
        raise FileNotFoundError(f"Designer template not found: {designer_path}")
    if not os.path.exists(installer_path):
        raise FileNotFoundError(f"Installer template not found: {installer_path}")
    
    # Read and encode Designer template
    with open(designer_path, "rb") as f:
        designer_bytes = f.read()
        designer_b64 = base64.b64encode(designer_bytes).decode('utf-8')
    
    # Read and encode Installer template
    with open(installer_path, "rb") as f:
        installer_bytes = f.read()
        installer_b64 = base64.b64encode(installer_bytes).decode('utf-8')
    
    # Generate Python module
    output_content = f'''# templates_base64.py
# Auto-generated by embed_templates.py
# DO NOT EDIT THIS FILE MANUALLY

"""
Base64-encoded .docx templates for the Art of Drawers Onboarding PDF Generator.
To update templates: modify files in templates/ folder and run embed_templates.py
"""

DESIGNER_DOCX_B64 = """{designer_b64}"""

INSTALLER_DOCX_B64 = """{installer_b64}"""
'''
    
    # Write to file
    output_path = "templates_base64.py"
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(output_content)
    
    print(f"✅ Successfully created {output_path}")
    print(f"   - Designer template: {len(designer_bytes):,} bytes")
    print(f"   - Installer template: {len(installer_bytes):,} bytes")
    print(f"   - Total base64 size: {len(designer_b64) + len(installer_b64):,} characters")


if __name__ == "__main__":
    embed_templates()
